apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-nodeapp

spec:
  replicas: 2

  selector:
    matchLabels:
      app: my-nodeapp

  template:
    metadata:
      labels:
        app: my-nodeapp

    spec:
      containers:
        - name: node-app
          image: 509461666868.dkr.ecr.us-east-1.amazonaws.com/my-node-app:v2
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
